version: "3"
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"

  tweet-harvester:
    build:
      context: ./tweet-harvester
      dockerfile: Dockerfile
    volumes:
      - ./tweet-harvester:/app/src
    ports:
      - "${HARVESTER_PORT}:${HARVESTER_PORT}"
    depends_on:
      - db
    env_file: 
      - ./tweet-harvester/.env
    environment:
      TWEET_PROCESSOR_URL: http://server
      TWEET_PROCESSOR_PORT: ${TWEET_PROCESSOR_PORT}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AUTH_TOKEN: ${AUTH_TOKEN}
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/src
    ports:
      - "${TWEET_PROCESSOR_PORT}:${TWEET_PROCESSOR_PORT}"
    depends_on:
      - db
    env_file: 
      - ./server/.env
    environment:
      HARVESTER_URL: http://tweet-harvester
      HARVESTER_PORT: ${HARVESTER_PORT}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AUTH_TOKEN: ${AUTH_TOKEN}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NITRO_PORT=${NITRO_PORT}
    volumes:
      - ./frontend:/app/src
    ports:
      - "${NITRO_PORT}:${NITRO_PORT}"
    depends_on:
      - db
    env_file: 
      - ./frontend/.env
    environment:
      NITRO_PORT: ${NITRO_PORT}
      NITRO_HOST: ${NITRO_HOST}
      AUTH_TOKEN: ${AUTH_TOKEN}
      NUXT_POSTGRES_HOST: db
      NUXT_POSTGRES_USER: ${POSTGRES_USER}
      NUXT_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NUXT_POSTGRES_DB: ${POSTGRES_DB}
      NUXT_POSTGRES_PORT: ${POSTGRES_PORT}
  
  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    volumes:
      - ./scheduler:/app/src
    ports:
      - "${SCHEDULER_PORT}:${SCHEDULER_PORT}"
    depends_on:
      - db
    env_file: 
      - ./scheduler/.env
    environment:
      SCHEDULER_PORT: ${SCHEDULER_PORT}
      AUTH_TOKEN: ${AUTH_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: db
      HARVESTER_URL: http://tweet-harvester
      HARVESTER_PORT: ${HARVESTER_PORT}
      TWEET_PROCESSOR_URL: http://server
      TWEET_PROCESSOR_PORT: ${TWEET_PROCESSOR_PORT}

volumes:
  db-data: