version: "3"
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    profiles:
      - all
      - db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    profiles:
      - all
      - db
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"

  harvester:
    build:
      context: ./harvester
      dockerfile: Dockerfile
    volumes:
      - ./harvester:/app/src
    ports:
      - "${HARVESTER_PORT}:${HARVESTER_PORT}"
    depends_on:
      - db
    profiles:
      - all
      - services
      - notdb
    env_file: 
      - ./harvester/.env
    environment:
      PROCESSOR_URL: http://processor
      PROCESSOR_PORT: ${PROCESSOR_PORT}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AUTH_TOKEN: ${AUTH_TOKEN}
      IR_PORT: ${IR_PORT}
      IR_URL: http://image-recognition
      USE_IR: false
  
  processor:
    build:
      context: ./processor
      dockerfile: Dockerfile
    volumes:
      - ./processor:/app/src
    ports:
      - "${PROCESSOR_PORT}:${PROCESSOR_PORT}"
    depends_on:
      - db
    profiles:
      - all
      - services
      - notdb
    env_file: 
      - ./processor/.env
    environment:
      HARVESTER_URL: http://harvester
      HARVESTER_PORT: ${HARVESTER_PORT}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      ML_PORT: ${ML_PORT}
      ML_URL: http://ml
      AUTH_TOKEN: ${AUTH_TOKEN}
      PROCESSOR_PORT: ${PROCESSOR_PORT}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGSMITH_PROJECT_NAME: ${LANGSMITH_PROJECT_NAME}
      RERANK_VECTOR_SEARCH_RESULTS: ${RERANK_VECTOR_SEARCH_RESULTS}
      ZERO_SHOT_CLASSIFY_TWEETS: ${ZERO_SHOT_CLASSIFY_TWEETS}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NITRO_PORT=${NITRO_PORT}
        - NITRO_HOST=${NITRO_HOST}
    volumes:
      - ./frontend:/app/src
    ports:
      - "${NITRO_PORT}:${NITRO_PORT}"
    depends_on:
      - db
    profiles:
      - all
      - services
      - notdb
    env_file: 
      - ./frontend/.env
    environment:
      NITRO_PORT: ${NITRO_PORT}
      NITRO_HOST: ${NITRO_HOST}
      AUTH_TOKEN: ${AUTH_TOKEN}
      NUXT_POSTGRES_HOST: db
      NUXT_POSTGRES_USER: ${POSTGRES_USER}
      NUXT_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NUXT_POSTGRES_DB: ${POSTGRES_DB}
      NUXT_POSTGRES_PORT: ${POSTGRES_PORT}
  
  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    volumes:
      - ./scheduler:/app/src
    ports:
      - "${SCHEDULER_PORT}:${SCHEDULER_PORT}"
    depends_on:
      - db
    profiles:
      - all
      - services
      - notdb
    env_file: 
      - ./scheduler/.env
    environment:
      SCHEDULER_PORT: ${SCHEDULER_PORT}
      AUTH_TOKEN: ${AUTH_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: db
      HARVESTER_URL: http://harvester
      HARVESTER_PORT: ${HARVESTER_PORT}
      PROCESSOR_URL: http://processor
      PROCESSOR_PORT: ${PROCESSOR_PORT}
  
  image-recognition:
    build:
      context: ./image-recognition-${IR_VERSION}
      dockerfile: ./docker/${IR_ENVIRONMENT}/Dockerfile
    volumes:
      - ./image-recognition-${IR_VERSION}:/app/src
    ports:
      - "${IR_PORT}:${IR_PORT}"
    profiles:
      - ir
    env_file: 
      - ./image-recognition-${IR_VERSION}/.env
    environment:
      IR_PORT: ${IR_PORT}
      IR_URL: ${IR_URL}
      AUTH_TOKEN: ${AUTH_TOKEN}
      IR_ENVIRONMENT: ${IR_ENVIRONMENT}
      IR_VERSION: ${IR_VERSION}
  
  ml:
    build:
      context: ./ml
      dockerfile: ./docker/${ML_ENVIRONMENT}/Dockerfile
    volumes:
      - ./ml:/app/src
    ports:
      - "${ML_PORT}:${ML_PORT}"
    profiles:
      - all
      - ml
      - notdb
    env_file: 
      - ./ml/.env
    environment:
      ML_PORT: ${ML_PORT}
      ML_URL: ${ML_URL}
      AUTH_TOKEN: ${AUTH_TOKEN}
      ML_ENVIRONMENT: ${ML_ENVIRONMENT}

volumes:
  db-data: